spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
  main:
    banner-mode: off
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 8848
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss}}){magenta} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(%-40.40logger{39}){cyan} %clr([%X{userId}=>%X{traceId}]){blue} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    com.github.maojx0630: debug
    org.apache.poi: info
mybatis:
  mapper-locations: classpath:/mapper/*.xml , classpath:/mapper/**/*.xml
  configuration:
    jdbc-type-for-null: 'null'
    map-underscore-to-camel-case: true
mybatis-plus:
  global-config:
    banner: false